<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class LocalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $path = database_path('data/localidades.sql');

        if (File::exists($path)) {
            $this->command->info('Cargando geometrías oficiales de localidades desde SQL...');
            
            // Clean up old data to ensure idempotency
            DB::statement('TRUNCATE localidades RESTART IDENTITY CASCADE');
            
            // Execute raw SQL geometry inserts generated by pg_dump
            DB::unprepared(file_get_contents($path));
            
            $this->command->info('¡Localidades cargadas con éxito!');
        } else {
            $this->command->error("No se encontró el archivo SQL en: {$path}. Por favor exporta los datos primero.");
        }
    }
}
